import { ArticleTemplate } from "./types";

const fonts = {
  sans: "-apple-system, BlinkMacSystemFont, 'PingFang SC', sans-serif",
  serif: "'Songti SC', STSong, serif",
};

export const templates: ArticleTemplate[] = [
  {
    id: "arena-poster",
    name: "竞橙 · 活动海报",
    category: "竞赛论坛",
    description: "深色海报首屏、编号章节和叠层卡片，强调现场规模与活动张力。",
    tags: ["竞赛", "论坛", "高密度", "海报"],
    motif: "01",
    layout: "poster",
    structure: ["海报首屏", "编号章节", "阴影内容卡", "金框现场图", "收束尾卡"],
    xiumiKeywords: ["黑橙 活动海报", "竞赛 公众号排版", "编号章节", "金色相框"],
    referenceIds: ["ref-competition-orange"],
    theme: {
      primary: "#34363c",
      secondary: "#fff4df",
      accent: "#f59b18",
      text: "#292929",
      muted: "#77736d",
      background: "#fffdf8",
      headingFont: fonts.sans,
      bodyFont: fonts.sans,
      radius: 2,
    },
  },
  {
    id: "blue-workshop",
    name: "澄澈 · 专业工作坊",
    category: "培训沙龙",
    description: "双主题栏、通栏现场图和轻量总结句，阅读节奏清楚舒展。",
    tags: ["培训", "沙龙", "清爽", "双主题"],
    motif: "02",
    layout: "workshop",
    structure: ["双线标题", "主题序号", "通栏大图", "摘要横条", "轻分隔"],
    xiumiKeywords: [
      "蓝色 培训活动",
      "工作坊 排版",
      "双栏标题",
      "简约 活动回顾",
    ],
    referenceIds: ["ref-workshop-blue"],
    theme: {
      primary: "#276da6",
      secondary: "#edf7ff",
      accent: "#55a9e8",
      text: "#243642",
      muted: "#70818d",
      background: "#ffffff",
      headingFont: fonts.sans,
      bodyFont: fonts.sans,
      radius: 8,
    },
  },
  {
    id: "cyan-youth",
    name: "向阳 · 青春成长",
    category: "青少年服务",
    description: "飘带小标题、拍立得图片与几何角标，活泼但保持专业克制。",
    tags: ["青少年", "成长", "活力", "图文交错"],
    motif: "03",
    layout: "youth",
    structure: ["青春封面", "飘带章节", "拍立得图组", "圆角色块", "签名结尾"],
    xiumiKeywords: ["青蓝 青少年", "拍立得 图文", "青春成长", "飘带标题"],
    referenceIds: ["ref-youth-cyan"],
    theme: {
      primary: "#168da8",
      secondary: "#e8faff",
      accent: "#70c9d7",
      text: "#23414a",
      muted: "#6f8990",
      background: "#fbfeff",
      headingFont: fonts.sans,
      bodyFont: fonts.sans,
      radius: 16,
    },
  },
  {
    id: "civic-blueprint",
    name: "协治 · 机制蓝图",
    category: "治理方案",
    description: "流程节点、双重点色和方案卡片，适合解释机制、路径与创新做法。",
    tags: ["政策", "机制", "流程", "治理"],
    motif: "04",
    layout: "blueprint",
    structure: ["蓝图封面", "步骤节点", "虚线机制卡", "双色结论", "方案闭环"],
    xiumiKeywords: [
      "蓝色 政策解读",
      "流程图 公众号",
      "机制建设",
      "蓝橙 信息图",
    ],
    referenceIds: ["ref-governance-blueprint"],
    theme: {
      primary: "#3c91bd",
      secondary: "#e8f6fc",
      accent: "#f2a267",
      text: "#203b49",
      muted: "#6d8793",
      background: "#fbfdfe",
      headingFont: fonts.sans,
      bodyFont: fonts.sans,
      radius: 10,
    },
  },
  {
    id: "warm-notebook",
    name: "暖笺 · 伦理笔记",
    category: "案例研讨",
    description: "纸张纹理、荧光标题和问题便签，适合知识拆解与案例复盘。",
    tags: ["伦理", "案例", "知识", "笔记"],
    motif: "05",
    layout: "notebook",
    structure: ["纸张题签", "荧光标题", "问题便签", "知识批注", "行动清单"],
    xiumiKeywords: [
      "奶油黄 笔记",
      "知识科普 排版",
      "便签 公众号",
      "荧光笔 标题",
    ],
    referenceIds: ["ref-ethics-warm"],
    theme: {
      primary: "#354d57",
      secondary: "#fff3d9",
      accent: "#ffd36a",
      text: "#313b3e",
      muted: "#7a8588",
      background: "#fffdf7",
      headingFont: fonts.sans,
      bodyFont: fonts.sans,
      radius: 5,
    },
  },
  {
    id: "redgold-award",
    name: "荣光 · 红金喜报",
    category: "获奖发布",
    description: "奖章式红金首屏、成果牌和金边照片，形成明确的庆典仪式感。",
    tags: ["获奖", "表彰", "成果", "喜报"],
    motif: "06",
    layout: "award",
    structure: ["奖章首屏", "获奖信息牌", "金边成果图", "成绩数字", "荣誉结语"],
    xiumiKeywords: ["红金 喜报", "获奖 表彰", "荣誉海报", "金边 图片"],
    referenceIds: ["ref-award-redgold"],
    theme: {
      primary: "#a92327",
      secondary: "#fff1dc",
      accent: "#dca94b",
      text: "#3d2724",
      muted: "#8e7169",
      background: "#fffaf2",
      headingFont: fonts.serif,
      bodyFont: fonts.sans,
      radius: 2,
    },
  },
  {
    id: "clinical-dossier",
    name: "专案 · 督导档案",
    category: "专业督导",
    description: "档案编号、侧边标签与诊断卡片，适合低图片密度的专业长文。",
    tags: ["督导", "个案", "报告", "长文"],
    motif: "07",
    layout: "dossier",
    structure: ["档案封套", "侧签章节", "诊断卡片", "低密度插图", "结案摘要"],
    xiumiKeywords: ["蓝灰 档案", "个案督导", "专业报告 排版", "侧边标签"],
    referenceIds: ["ref-case-dossier"],
    theme: {
      primary: "#517eaf",
      secondary: "#f0f3f5",
      accent: "#91adcb",
      text: "#2c3944",
      muted: "#74818b",
      background: "#ffffff",
      headingFont: fonts.sans,
      bodyFont: fonts.sans,
      radius: 14,
    },
  },
  {
    id: "ink-magazine",
    name: "留白 · 人物杂志",
    category: "深度人物",
    description: "超大标题、编辑编号和不对称留白，呈现纸媒般的深度叙事感。",
    tags: ["人物", "访谈", "深度", "杂志"],
    motif: "08",
    layout: "magazine",
    structure: ["杂志刊头", "大字标题", "不对称图片", "引语跨页", "编辑尾注"],
    xiumiKeywords: ["黑白 杂志", "人物专访", "极简 留白", "大字标题"],
    referenceIds: [],
    theme: {
      primary: "#171717",
      secondary: "#f0efeb",
      accent: "#9a2428",
      text: "#202020",
      muted: "#85817b",
      background: "#ffffff",
      headingFont: fonts.serif,
      bodyFont: fonts.sans,
      radius: 0,
    },
  },
  {
    id: "service-timeline",
    name: "历程 · 行动时间轴",
    category: "项目复盘",
    description: "纵向时间线串联行动节点，适合呈现活动过程、阶段成果和下一步。",
    tags: ["历程", "复盘", "节点", "项目"],
    motif: "09",
    layout: "timeline",
    structure: ["项目序章", "纵向时间轴", "节点圆标", "阶段图片", "下一步计划"],
    xiumiKeywords: ["时间轴 公众号", "项目复盘", "活动历程", "绿色 节点"],
    referenceIds: ["ref-workshop-blue", "ref-youth-cyan"],
    theme: {
      primary: "#386b5a",
      secondary: "#edf5f0",
      accent: "#cd9551",
      text: "#293a33",
      muted: "#74837d",
      background: "#fcfdfb",
      headingFont: fonts.serif,
      bodyFont: fonts.sans,
      radius: 9,
    },
  },
  {
    id: "photo-gallery",
    name: "现场 · 影像叙事",
    category: "活动纪实",
    description: "暗色片头、胶片编号与大图节奏，让图片成为文章的主要叙事线。",
    tags: ["摄影", "现场", "大图", "纪实"],
    motif: "10",
    layout: "gallery",
    structure: ["暗场片头", "胶片编号", "大图序列", "短句旁白", "影像尾帧"],
    xiumiKeywords: ["摄影 画册", "活动纪实", "胶片 排版", "黑色 大图"],
    referenceIds: ["ref-competition-orange", "ref-award-redgold"],
    theme: {
      primary: "#263238",
      secondary: "#ece9e2",
      accent: "#d56b43",
      text: "#303536",
      muted: "#7c7d79",
      background: "#faf9f5",
      headingFont: fonts.sans,
      bodyFont: fonts.sans,
      radius: 1,
    },
  },
];

export const defaultPrompt = `你是一位资深微信公众号编辑与视觉排版设计师。请完整保留新闻事实，不得编造人物、数据和结论。优化标题、导语和段落层级，使语言准确、简洁、自然。根据素材语义安排图片，在保持正式感的同时提升移动端阅读体验。输出必须遵循所选模板的配色、留白、结构骨架和组件规则，并且只使用微信公众号兼容的内容结构。

必须遵守以下公众号正文排版规范：
1. 每个普通正文段落首行缩进两个汉字（2em）。
2. 正文行间距为 2，字间距为 0。
3. 正文内容字号统一为 16px。
4. 普通正文、导语、引用和提示内容使用黑色；仅标题、章节标题及装饰元素可按照模板使用彩色。
5. 文章结尾必须出现清晰的“END”标识，允许结合模板添加装饰，但不得省略 END。`;

export function getTemplate(id?: string) {
  return templates.find((item) => item.id === id) ?? templates[0];
}
